### ISSUE TITLE
[Bug]: web browser is not cross platform

### ISSUE THREAD

**Issue by ama-coder** [parch-os/doogh-shell#2]
### What happened?

A bug happened!

web browser running :  xdg-open
this is not avalable defaultly on mac and windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ama-coder** [comment]
you can use this arch :

-dogh.py
-windows.py
-mac.py
-linux.py

and in base(dogh.py) get os type an use one of this modules.

you can use cross platform core-utils and tools and compile  those in build time to a shared/dynamic library or get binerys from server and use on python source.

**Comment by mmdbalkhi** [comment]
What do you think? @bsslinux

**Comment by bsslinux** [comment]
> What do you think? @bsslinux

Now that you are wasting my efforts, you will delete everything I code for two hours.
Do whatever you like when you do not let me code.

**Comment by bsslinux** [comment]
> Yes, I know there is no such thing in Windows, so I defined an if that detects the platform and runs the browser accordingly.

**Comment by mmdbalkhi** [comment]
> > What do you think? @bsslinux
> 
> Now that you are wasting my efforts, you will delete everything I code for two hours. Do whatever you like when you do not let me code.

np. I solved it in d92ecea87ed3328fe4d4e6c73723e6ad35d3acff

**Comment by ama-coder** [comment]
داداش من متوجه نشدم چی شد میشه فارسی بگین؟

**Comment by bsslinux** [comment]
> داداش من متوجه نشدم چی شد میشه فارسی بگین؟

کد رو به کل بازنویسی کردیم و تغییرات زیادی دادیم توش

**Comment by ama-coder** [comment]
آهان. سورس رو نگاه نکردم. نظرتون راجع به استفاده از تولز و نرم افزار های خارجی چیه؟

**Comment by bsslinux** [comment]
> آهان. سورس رو نگاه نکردم. نظرتون راجع به استفاده از تولز و نرم افزار های خارجی چیه؟

در چه چیزی؟

**Comment by ama-coder** [comment]
همونطور که در بالا توضیح دادم شل هایی مثل بش بجای اینکه همه ی کامند هارو داخل سورس نوشته باشن نرم افزار هارو اجرا میکنن. مثلا ال اس یه نرم افزاره نه یه فانکشن داخل خود بش. فکر کنم مسیرشم user/bin/ls  باشه

**Comment by ama-coder** [comment]
یه تغییر باحالی دارم تو سرس میدم چند دیقه دیگه پول ریکویست میزنم

**Comment by bsslinux** [comment]
> یه تغییر باحالی دارم تو سرس میدم چند دیقه دیگه پول ریکویست میزنم

تغیر رو دادین بی زحمت توی دیسکورد پیام بدین

**Comment by bsslinux** [comment]
چون این ایشو خیلی وقته بسته شده

**Comment by ama-coder** [comment]
میدونم.  ببخشید الان به دیسکورد دسترسی ندارم. پول ریکویست میزنم.

**Comment by bsslinux** [comment]
> میدونم.  ببخشید الان به دیسکورد دسترسی ندارم. پول ریکویست میزنم.

اشکالی نداره

**Comment by ama-coder** [comment]
یه چیزی من داشتم کودو میخوندم چرا بعضی از کامند ها مثل ls تو کلس هست ولی پیاده سازی نشده؟

**Comment by ama-coder** [comment]
فکر کنم فقط ال اس اینجوریه. تو کد ال اس url چیه؟ تعریف هم نشده. من تو ورژن خودم تغییرش دادم.

**Comment by ama-coder** [comment]
فکر کنم کودش با webbrowser قاطی شده
